Fix importsNotUsedAsValues ts error
```
node_modules/react-native-anchor-point/index.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
```